const apiFolders = {
  title: "SUREPASS API",
  folders: [
    {
      name: "PAN",
      subfolders: [
        {
          name: "PAN Verification",
          endpoint: "/pan/verification",
          method: "POST",
          requestExample: {
            product_code: "API0001",
            trans_id: "BV576862_1234567890",
            pan_no: "ASXXXXX75J",
          },
          responseExample: {
            trans_id: "BV576862_1234567890",
            status: "success",
            message: "pan verification successful",
            pan_no: "ASXXXXX75J",
            fullname: "BHUSHAN RAGHUNATH VISHE",
            category: "person",
            pan_status: "valid",
            upstream_rrn: "pan_OhMyzrRngvjfghpSuiZZ",
          },
        },
        {
          name: "PAN Comprehensive",
          endpoint: "/pan/comprehensive",
          method: "POST",
          requestExample: {
            product_code: "API0002",
            trans_id: "BV576862_1234567891",
            pan_no: "ASXXXXX75J",
          },
          responseExample: {
            trans_id: "BV576862_1234567891",
            status: "success",
            message: "pan verification successful",
            pan_no: "ASXXXXX75J",
            firstname: "BHUSHAN",
            middlename: "RAGHUNATH",
            lastname: "VISHE",
            fullname: "BHUSHAN RAGHUNATH VISHE",
            dob: "1992-06-06",
            pan_status: "valid",
            pan_status_code: "E",
            gender: "M",
            email: "bhushanrvishe@gmail.com",
            phone_number: "8975168703",
            aadhaar_link_status: true,
            masked_aadhaar: "XXXXXXXX5582",
            address: {
              line1: "H.No. 84",
              line2: "Near Hanuman Mandir",
              street: "at-post:Pashane,Tal:Karjat",
              state: "MAHARASHTRA",
              city: "RAIGARH(MH)",
              pincode: "410201",
              country: "INDIA",
              full_address:
                "H.No. 84 Near Hanuman Mandir at-post:Pashane,Tal:Karjat 410201 RAIGARH(MH) MAHARASHTRA INDIA",
            },
            upstream_rrn: "pan_comprehensive_ahrTLLAbeRaJXpdrdSvy",
            category: "person",
          },
        },
      ],
    },
    {
      name: "Aadhaar",
      subfolders: [
        {
          name: "AADHAAR Generate Otp",
          endpoint: "/aadhaar/generate-otp",
          method: "POST",
          requestExample: {
            product_code: "API0003",
            trans_id: "BV576862_1234567891",
            aadhaar_no: "XXXXXXXX5582",
          },
          responseExample: {
            trans_id: "BV576862_1234567891",
            aadhaar_no: "XXXXXXXX5582",
            status: "success",
            message: "otp sent on aadhaar registered mobile number",
            is_otp_sent: true,
            otp_reference_no: "aadhaar_v2_YxfeokIhjlucpWooNbpr",
          },
        },
        {
          name: "AADHAAR Validate Otp",
          endpoint: "/aadhaar/validate-otp",
          method: "POST",
          requestExample: {
            product_code: "API0004",
            trans_id: "BV576862_1234567892",
            otp_reference_no: "aadhaar_v2_YxfeokIhjlucpWooNbpr",
            otp: "745618",
          },
          responseExample: {
            data: {
              client_id: "aadhaar_v2_YxfeokIhjlucpWooNbpr",
              full_name: "Bhushan Raghunath Vishe",
              aadhaar_number: "XXXXXXXXXXXX",
              dob: "1992-06-06",
              gender: "M",
              address: {
                country: "India",
                dist: "Raigarh",
                state: "Maharashtra",
                po: "Manivali",
                loc: "Pashane",
                vtc: "Pashane",
                subdist: "Karjat",
                street: "",
                house: "House No. 84",
                landmark: "Near Hanuman Mandir",
              },
              face_status: false,
              face_score: -1,
              zip: "410101",
              profile_image: "base64 image",
              has_image: true,
              email_hash:
                "087fa3a9c8760b444fa87dd3df69eafc9f6e4c36eb64105cb7224783ad515903",
              mobile_hash:
                "f216eafdc7707ddff74366e8c1965a114d92ccc5a43aa04a7439f1556eb5ca4f",
              raw_xml: "xml url",
              zip_data: "zip kyc data folder url",
              care_of: null,
              share_code: "3990",
              mobile_verified: false,
              reference_id: "558220241010185833327",
              aadhaar_pdf: null,
              status: "success_aadhaar",
              uniqueness_id:
                "c26d044ec7ba81e9e37792af70c523c0ab3b0d5d02048f20b5be811aec166d31",
            },
            trans_id: "BV576862_1234567892",
            status: "success",
            message: "aadhaar submit otp verified successfully",
            upstream_rrn: "aadhaar_v2_YxfeokIhjlucpWooNbpr",
          },
        },
        {
          name: "AADHAAR Basic Verification",
          endpoint: "/aadhaar/verification",
          method: "POST",
          requestExample: {
            product_code: "API0005",
            trans_id: "BV576862_1234567893",
            aadhaar_no: "712489735582",
          },
          responseExample: {
            trans_id: "BV576862_1234567893",
            status: "success",
            message: "aadhaar verification successful",
            upstream_rrn: "aadhaar_validation_obcwQfxHqblhBhxwqnrT",
            aadhaar_no: "712489735582",
            aadhaar_status: "valid",
            age_range: "30-40",
            gender: "M",
            is_mobile_linked: true,
            mobile_last_digits: "380",
            state: "Maharashtra",
          },
        },
      ],
    },
    {
      name: "Bank",
      subfolders: [
        {
          name: "Bank Account",
          endpoint: "/bank/account",
          method: "POST",
          requestExample: {
            product_code: "API0006",
            trans_id: "BV576862_1234567894",
            bank_account_no: "1234567890",
            ifsc_code: "SBIN0001234",
          },
          responseExample: {
            trans_id: "BV576862_1234567894",
            status: "success",
            message: "bank account verification successful",
            account_holder_name: "John Doe",
            bank_name: "State Bank of India",
          },
        },
        {
          name: "Bank Account Penny Drop",
          endpoint: "/bank/penny-drop",
          method: "POST",
          requestExample: {
            product_code: "API0007",
            trans_id: "BV576862_1234567895",
            bank_account_no: "1234567890",
            ifsc_code: "SBIN0001234",
          },
          responseExample: {
            trans_id: "BV576862_1234567895",
            status: "success",
            message: "Penny drop successful",
            transaction_id: "TRX1234567890",
          },
        },
      ],
    },
    {
      name: "GST",
      subfolders: [
        {
          name: "Basic GST",
          endpoint: "/gst/basic",
          method: "POST",
          requestExample: {
            product_code: "API0006",
            trans_id: "BV576862_1234567894",
            gstin: "27AXXXXXXX8M1ZP",
          },
          responseExample: {
            trans_id: "BV576862_1234567894",
            status: "success",
            message: "GST verification successful",
            gstin: "27AXXXXXXX8M1ZP",
            gstin_status: "valid",
            registration_date: "2023-09-08",
            registration_type: "Private Limited Company",
            registration_name: "REGISTER NAME OF COMPANY",
            nature_of_business_activities:
              "Office / Sale Office|Retail Business|Supplier of Services|Works Contract",
            e_invoicing_status: "NO",
            legal_name_of_business: "LEGAL NAME OF COMPANY",
            constitution_of_business: "Private Limited Company",
            centre_jurisdiction:
              "State - CBIC,Zone - MUMBAI,Commissionerate - BHIWANDI,Division - DIVISION IV,Range - RANGE-I (Jurisdiction)",
            error: {},
          },
        },
        {
          name: "Comprehensive GST",
          endpoint: "/gst/comprehensive",
          method: "POST",
          requestExample: {
            product_code: "API0007",
            trans_id: "BV576862_1234567895",
            gstin: "27AXXXXXXX8M1ZP",
          },
          responseExample: {
            trans_id: "BV576862_1234567895",
            status: "success",
            message: "GST verification successful",
            gstin: "27AXXXXXXX8M1ZP",
            gstin_status: "valid",
            registration_date: "2023-09-08",
            registration_type: "Private Limited Company",
            registration_name: "REGISTER NAME OF COMPANY",
            nature_of_business_activities:
              "Office / Sale Office|Retail Business|Supplier of Services|Works Contract",
            e_invoicing_status: "NO",
            legal_name_of_business: "LEGAL NAME OF COMPANY",
            constitution_of_business: "Private Limited Company",
            centre_jurisdiction:
              "State - CBIC,Zone - MUMBAI,Commissionerate - BHIWANDI,Division - DIVISION IV,Range - RANGE-I (Jurisdiction)",
            error: {},
          },
        },
      ],
    },
  ],
};

export default apiFolders;
